name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -sS -o /dev/null -w "%{http_code}\n" https://xeduyt2kf49xgek76.streamlit.app
          echo "Streamlit pinged successfully"
