name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s https://xeduyt2kf49xgek76.streamlit.app > /dev/null
          echo "Streamlit pinged successfully"
